version: '3'
services:
  db:
    image: mysql:5.7
    container_name: 'django_db'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'django_app'
